syntax on
colorscheme dracula
set nocompatible
set ruler
set showcmd
set guifont=Source_Code_Pro:h11:cANSI:qDRAFT
set nowrap
set tabstop=4
set showmatch
set smartcase
set incsearch
set ignorecase
set nu
set rnu
"set foldmethod=syntax
set history=1000
set undolevels=1000
set title
set noswapfile
set nobackup
nnoremap ; :
set noerrorbells
set autochdir
